# Generated by Django 3.2.5 on 2021-07-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=120)),
                ('check', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
