# Generated by Django 2.2.8 on 2021-08-13 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=120)),
                ('check', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
